# Using data_handler.py

The main idea is to read the edf files and extract the data from the summary files too. This is a simple demo.

In [23]:
from sz_utils import data_handler

# get all patient labels
patients = data_handler.get_patients()
print("Patients\n", patients)

# get all edf files in a patient
edf_files = data_handler.get_patient_edf(patients[0])
print(f"\nEDF files in patient {patients[0]}\n", edf_files)

# get the summary of a patient
summary = data_handler.get_summary(patients[0])
print(f"\nSummary of patient {patients[0]} (first 200 chars)\n", summary[:200])

Patients
 ['chb01', 'chb02', 'chb03', 'chb04', 'chb05', 'chb06', 'chb07', 'chb08', 'chb09', 'chb10', 'chb11', 'chb12', 'chb13', 'chb14', 'chb15', 'chb16', 'chb17', 'chb18', 'chb19', 'chb20', 'chb21', 'chb22', 'chb23', 'chb24']

EDF files in patient chb01
 ['chb01_01.edf', 'chb01_02.edf', 'chb01_03.edf', 'chb01_04.edf', 'chb01_05.edf', 'chb01_06.edf', 'chb01_07.edf', 'chb01_08.edf', 'chb01_09.edf', 'chb01_10.edf', 'chb01_11.edf', 'chb01_12.edf', 'chb01_13.edf', 'chb01_14.edf', 'chb01_15.edf', 'chb01_16.edf', 'chb01_17.edf', 'chb01_18.edf', 'chb01_19.edf', 'chb01_20.edf', 'chb01_21.edf', 'chb01_22.edf', 'chb01_23.edf', 'chb01_24.edf', 'chb01_25.edf', 'chb01_26.edf', 'chb01_27.edf', 'chb01_29.edf', 'chb01_30.edf', 'chb01_31.edf', 'chb01_32.edf', 'chb01_33.edf', 'chb01_34.edf', 'chb01_36.edf', 'chb01_37.edf', 'chb01_38.edf', 'chb01_39.edf', 'chb01_40.edf', 'chb01_41.edf', 'chb01_42.edf', 'chb01_43.edf', 'chb01_46.edf']

Summary of patient chb01 (first 200 chars)
 Data Sampling Rate: 256 Hz
*************************

Channels in EDF Files:
**********************
Channel 1: FP1-F7
Channel 2: F7-T7
Channel 3: T7-P7
Channel 4: P7-O1
Channel 5: FP1-F3
Channel 6: F3

In [25]:
# get the raw edf data
edf_data = data_handler.get_edf_data(patients[0], edf_files[0])
print(f"\nEDF Data of patient {patients[0]} and file {edf_files[0]} (first 5 rows)\n")
edf_data.head()

Extracting EDF parameters from /mnt/e/Documents/projects/seizure-prediction/data/chb-mit-scalp-eeg-database-1.0.0/chb01/chb01_01.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...

/home/mnsosa/projects/SeizurePrediction/src/sz_utils/data_handler.py:74: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8'}. Applying running numbers for duplicates.
  mne_data = mne.io.read_raw_edf(edf_path)

EDF Data of patient chb01 and file chb01_01.edf (first 5 rows)

,time,FP1-F7,F7-T7,T7-P7,P7-O1,FP1-F3,F3-C3,C3-P3,P3-O1,FP2-F4,...,F8-T8,T8-P8-0,P8-O2,FZ-CZ,CZ-PZ,P7-T7,T7-FT9,FT9-FT10,FT10-T8,T8-P8-1
0,0.000000,-145.934066,-104.517705,-42.783883,-33.015873,-170.940171,-110.769231,11.916972,-56.459096,-139.291819,...,57.240537,44.737485,74.822955,-106.080586,84.590965,43.174603,-57.240537,-264.713065,94.749695,44.737485
1,0.003906,0.195360,0.195360,0.195360,0.195360,0.195360,0.195360,0.195360,0.195360,0.195360,...,0.195360,0.195360,0.195360,0.195360,0.195360,0.195360,0.195360,0.195360,0.195360,0.195360
2,0.007812,0.195360,0.195360,0.195360,0.195360,0.195360,0.195360,0.195360,0.195360,0.195360,...,0.195360,0.195360,-0.195360,0.195360,0.195360,0.195360,0.195360,0.586081,0.195360,0.195360
3,0.011719,0.195360,0.586081,0.195360,0.586081,0.195360,0.195360,0.195360,0.195360,0.195360,...,1.367521,0.195360,-2.148962,0.195360,0.195360,0.195360,-0.586081,1.758242,0.195360,0.195360
4,0.015625,0.195360,0.195360,0.195360,-0.195360,0.195360,0.195360,0.195360,0.195360,0.195360,...,0.195360,0.195360,0.976801,0.195360,0.195360,0.195360,0.586081,-2.148962,0.195360,0.195360

In [30]:
# get the seizure data
seizure_data = data_handler.get_seizure_data(patients[0])
seizure_data.head()

      file_name  number_of_seizures start_end_times
0  chb01_01.edf                   0             NaN
1  chb01_02.edf                   0             NaN
2  chb01_03.edf                   1  [(2996, 3036)]
3  chb01_04.edf                   1  [(1467, 1494)]
4  chb01_05.edf                   0             NaN

In [33]:
# filter seizure data by number of seizures > 0
seizure_data[seizure_data["number_of_seizures"] > 0]

       file_name  number_of_seizures start_end_times
2   chb01_03.edf                   1  [(2996, 3036)]
3   chb01_04.edf                   1  [(1467, 1494)]
14  chb01_15.edf                   1  [(1732, 1772)]
15  chb01_16.edf                   1  [(1015, 1066)]
17  chb01_18.edf                   1  [(1720, 1810)]
20  chb01_21.edf                   1    [(327, 420)]
25  chb01_26.edf                   1  [(1862, 1963)]

In [46]:
# the start and end times has a str format.
# an example on how to convert it to a list of tuples
example = seizure_data[seizure_data["number_of_seizures"] > 0]["start_end_times"]
example = example.values[0]

print(type(example))
example

<class 'str'>

'[(2996, 3036)]'

In [50]:
# convert the str '[(2996, 3036)]' to a list of tuples
import ast

result = ast.literal_eval(example)
print(type(result))
print(result)
print(result[0][0])
print(type(result[0][0]))

<class 'list'>
[(2996, 3036)]
2996
<class 'int'>